version: "3"

services:
  nginx:
    build:
      context: .
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
    container_name: app-b
    networks:
      - app-b-network

networks:
  app-b-network:
