version: "3"

services:
  nginx:
    build:
      context: .
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    container_name: app-a
    networks:
      - app-a-network

networks:
  app-a-network:
