version: "3.7"

services:
  nginx:
    build:
      context: .
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    container_name: app-a
    networks:
      - app-a-network
    extra_hosts:
      - "service-b:172.16.1.1"

networks:
  app-a-network:
  default:
    external:
      name: b_app-b-network
